### ISSUE TITLE
How to compile and run miniedit on linux?

### ISSUE THREAD

**Issue by tarrsalah** [parmaja/miniedit#32]
Is there any solution to create a `Makefile` or some script to automatically generate a binary? 

I tried  `lazbuild  source/gui/mne.lpi`, I get a broken dependency error:

```
primary config path: /home/tarrsalah/.lazarus
TBuildManager.SetBuildTarget Old=x86_64-linux-gtk2 New=x86_64-linux-gtk2 FPC=True LCL=False
TBuildManager.SetBuildTarget Old=x86_64-linux-gtk2 New=x86_64-linux-gtk2 FPC=True LCL=False
ERROR: Broken dependency: cmdbox
  ```

**Comment by zaher** [comment]
You need this packages

* MiniLib http://sourceforge.net/projects/minilib
* CMDBox http://wiki.freepascal.org/CmdLine
 
 You need to install all packages that needed 

CMDBox package

    CMDLine\cmdbox.dpk

minilib pachages

    minilib\lib\MiniCommons.lpk
    minilib\xml\source\MiniXML.lpk
    minilib\socket\source\MiniSockets.lpk
    minilib\connection\source\MiniConnections.lpk
    minilib\comm\source\MiniComm.lpk
    minilib\connection\db\MiniDB.lpk
    minilib\lazarus\lib\MiniLib.lpk
    minilib\lazarus\components\native\NativeLib.lpk

Build minilib project

I updated the readme

**Comment by tarrsalah** [comment]
Unfortunately, I can't build the binary even when installing all the needed packages.

**Comment by zaher** [comment]
What the error? 
All you need to install FPC lastversion, Lazarus from SVN repo, not last release, idk if it will work with older release, try it.
now CMD and Minilib package to install let us try with first package 
minilib\lib\MiniCommons.lpk
To install it in Lazaurs IDE->Menu->Package->Open Package File
open MiniCommons.lpk and compile it, then click: "Use"->Install

**Comment by tarrsalah** [comment]
I get errors when compiling `MiniCommons.lpk`, I'm using `lazarus_1.4.4-0` and `fpc_2.6.4-150228`:

``
Compiling package MiniCommons 1.0.1: Exit code 1, Errors: 1, Hints: 1
mnFields.pas(761,20) Error: Calling convention doesn't match forward
mnFields.pas(213,14) Hint: Found declaration: TmnFields.QueryInterface(constref TGuid,out <Formal type>):LongInt; CDecl;``




![screenshot - 01 2016 - cet 02 52 24](https://cloud.githubusercontent.com/assets/909959/12069482/bf56a2be-b032-11e5-8854-a08977015ba3.png)

**Comment by zaher** [comment]
Yes it is a bug, I fixed it, update minilib and try again.

Hmm that help me to fix bugs in Linux thank you ^.^

**Comment by tarrsalah** [comment]
Good work @zaher :+1: , I updated  `minilib` and `MiniCommons.lpk` compiles and looks fine and dandy :v: ,  Now I have another issue when compiling `MiniDB,lpk` package:
```
Compiling package MiniConnections 1.0.1: Success
Compiling package MiniDB 0.0: Exit code 1, Errors: 2
mncSQLiteHeader.pas(188,40) Error: Identifier not found "external"
mncSQLiteHeader.pas(188,48) Error: Error in type definition
```
---
![minidb-bug](https://cloud.githubusercontent.com/assets/909959/12070910/1d412e4a-b091-11e5-9bf0-8080afce29f2.png)
---

I really wish that I can help with the code.

**Comment by zaher** [comment]
Fixed, try it again :P 
in fact the better way is to install linux on my pc, but you know we have no time

**Comment by zaher** [comment]
You can just paste the error text, no need for images

**Comment by tarrsalah** [comment]
Done with `MiniDB.lpk` :+1: 

* Now with `MiniLib.lpk`:
```
Compiling package MiniLib 0.0: Exit code 1, Errors: 2
SynHighlighterFirebird.pas(621,13) Error: Illegal type conversion: "TRangeState" to "Pointer"
SynHighlighterFirebird.pas(681,13) Error: Illegal type conversion: "Pointer" to "TRangeState"
```

**Comment by zaher** [comment]
I modified it, but not sure it work, try and confirm.

**Comment by tarrsalah** [comment]
Well, now with `MiniDB.lpk` again, maybe caused by your last commit !

```
Compiling package MiniDB 0.0: Exit code 1, Errors: 3
mncFBHeader.pas(53,30) Error: Identifier not found "sharedsuffix"
mncFBHeader.pas(53,42) Error: Illegal expression
mncFBHeader.pas(53,43) Error: 
```

**Comment by zaher** [comment]
That was expected, try now

**Comment by tarrsalah** [comment]
Another issue
```
Compiling package MiniCommons 1.0.1: Success
Compiling package MiniConnections 1.0.1: Success
Compiling package MiniDB 0.0: Exit code 1, Errors: 1
mncFBClient.pas(21,13) Fatal: Cannot find unit Windows used by mncFBClient of package MiniDB.
```

**Comment by zaher** [comment]
Do not compile MiniDB, I removed this package from miniEdit, update MiniEdit then compile the rest of packages

MiniDB i will use it in the future when add SQL engine inside it.

**Comment by tarrsalah** [comment]
Ok, now it seems that all the dependencies are successfully compiles, back the `miniedit` problems:

I have a this error:

```
MainUnit.pas(1929,18) Error: identifier idents no member "Clear"
```

**Comment by zaher** [comment]
Fixed, update it

**Comment by tarrsalah** [comment]
Another compile error:
`mneAssociateForm.pas(35,15) Error: Forward declaration not solved "TAssociateForm.AddEdit;"`

**Comment by zaher** [comment]
Done, wow we are on the road :)

**Comment by tarrsalah** [comment]
Well, I know that''s too late in Syria now, but there is another error:
```
mnePHPClasses.pas(349,16) Error: Identifier not found "SelectorAttri"
mnePHPClasses.pas(353,16) Error: Identifier not found "MeasurementUnitAttri" 
```

**Comment by zaher** [comment]
Ah, there is a lot of error like that, you need to take last subversion of Lazarus, if you failed you can use snapshot one, or give me your revision of the Lazarus that u r using it from About, i will try to make some backward compatibility.

**Comment by tarrsalah** [comment]
I'm using `lazarus_1.4.4-0`, and I think that it's the last version available here http://sourceforge.net/projects/lazarus/files/.

**Comment by zaher** [comment]
I am using subversion, i got it from the source directly, to be with last changes.
ok, i will try to make backward compatibility tomorrow.

**Comment by tarrsalah** [comment]
Ok, thanks for the support :+1: @zaher

**Comment by zaher** [comment]
I fixed it, please update miniedit and tell me it is compiled :)

**Comment by tarrsalah** [comment]
Finally !! :v:

----
![minieditfinally](https://cloud.githubusercontent.com/assets/909959/12074478/bdd7b160-b156-11e5-8f48-ac653f71484c.png)

---

Thank you for your time @zaher , I'm really excited to contribute to your projects.

**Comment by zaher** [comment]
Waha, finally, it is a dream  for me 😍

**Comment by zaher** [comment]
You are welcome @tarrsalah, I think there is many bugs related to linux, when u find it, you can add pull request, or new issue.

**Comment by tarrsalah** [comment]
Ok, I'm in the process of learning some free pascal/lazarus now , I'm really excited to update to `fpc 3.0.0`  and `Lazarus 1.6.0`, I will really appreciate moving [minilib](http://sourceforge.net/projects/minilib/) source here, so I can read the source and maybe fix some linux related issues.

Thanks again @zaher .
